### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/oppsy#11]
Is this module still used? If it is, please close pending issues and PRs and open a hapi v17 migration issue. Otherwise, let's deprecate it.

**Comment by arb** [comment]
Used by good so it depends what we do with that.

**Comment by geek** [comment]
@arb I'm happy to take oppsy over if you want, I'm using it elsewhere.

**Comment by corbinu** [comment]
Updated!

**Comment by corbinu** [comment]
@arb looks like the 2.0.0 version was cut but isn’t on npm just wondering about progress thanks so much!

**Comment by arb** [comment]
Ops. 2.0.0 should be on the registry now.
