### ISSUE TITLE
GC metrics

### ISSUE THREAD

**Issue by StianOvrevage** [hapijs/oppsy#14]
Thanks for still maintaining Oppsy! I spent all day yesterday comparing various Hapi and Node metrics reporting plugins and Oppsy is by far the most complete, as well as being the only one ported to v17.

I do have one question/request, for garbage collection (GC) metrics. None of the other plugins have this currently, but reading up on NodeJS performance and monitoring it seems having info on specifically GC time/duration, number of full and incremental GCs would be useful.

**Comment by corbinu** [comment]
@StianOvrevage Unfortunately in a little digging looks like the only way to do this is with a native extension: https://github.com/bretcope/node-gc-profiler

However if you found something that allows this in JavaScript I could take a look.
