### ISSUE TITLE
Cannot read property 'statusCodes' of undefined

### ISSUE THREAD

**Issue by cgatesman** [hapijs/oppsy#17]
hapi: 17.5.4
good: 8.1.1
good-squeeze: 5.1.0

My application crashes with an unhandled promise rejection when using good along with a takeover redirect in a onRequest.

I had opened https://github.com/hapijs/good/issues/597 with Good thinking it was a problem there, but it looks like it's more of a problem in Oppsy and goes away when I disable Oppsy in Good.

Although I'm not using it, a simple example of this is to use hapi-require-https and don't setup https:

```javascript
server.register({
  plugin: require('hapi-require-https'),
  options: {
    proxy: false
  }
});
```

My current good configuration is as follows, but it doesn't seem to matter how simple I make it.  The crash always occurs:

```javascript
  await server.register({
    plugin: require('good'),
    options: {
      ops: {
        interval: 1000
      },
      reporters: {
        myConsoleReporter: [
          {
            module: 'good-squeeze',
            name: 'Squeeze',
            args: [{log: '*', response: '*'}]
          },
          {
            module: 'good-console'
          },
          'stdout'
        ]
      }
    }
  });
```

With this setup, when you hit your application using `http`, it crashes with an unhandled promise rejection when it tries to redirect (301) to https:

```
SEVERE: Unhandled promise rejection!
Promise: Promise {
  <rejected> TypeError: Cannot read property 'statusCodes' of undefined
    at Network._server.events.on (/Users/chad/development/np-pillars/node_modules/oppsy/lib/network.js:56:38)
    at module.exports.internals.Podium.internals.Podium.emit (/Users/chad/development/np-pillars/node_modules/podium/lib/index.js:220:49)
    at Request._finalize (/Users/chad/development/np-pillars/node_modules/hapi/lib/request.js:388:27)
    at Request._reply (/Users/chad/development/np-pillars/node_modules/hapi/lib/request.js:350:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) } 
```

**Comment by arb** [comment]
It looks like the server being passed in to `oppsy` doesn't have the `port` value set? https://github.com/hapijs/oppsy/blob/master/lib/network.js#L21

This makes me think the issue is in hapi-require-https?

**Comment by cgatesman** [comment]
How would it be a problem in hapi-require-https?  It's just doing a h.redirect() to https://_requestedHost_/_requestedPath_.  Surely it's not required to specify a port on the redirect URL.

**Comment by cgatesman** [comment]
I put a breakpoint on that line, and it never even gets into that `onRequest` callback.

**Comment by cgatesman** [comment]
I found that if I register hapi-require-https _after_ good, the issue goes away.  This works.  It's just unfortunate that it's not really something that is obvious up front for the developer when registering the plugins.

**Comment by hueniverse** [comment]
@arb does it make sense to use the `after` option in dependency? Not sure how this is loaded and if it requires good.

**Comment by arb** [comment]
Looking back at https://github.com/hapijs/good/issues/360 makes me think the issue is that the server doesn't have a connection yet. While this shouldn't impact the operation of oppsy, that is likely the issue here. 

Good + Oppsy are very loosely coupled so I don't think `after` would help in this case. Is there anything new in the hapi api that stipulates a plugin requires a connection to work correctly?

**Comment by hueniverse** [comment]
@cgatesman still a problem?

**Comment by cgatesman** [comment]
Sorry, I haven't had a chance to work on the project that had this issue.  Note, we had worked around it by changing the order of the registering: https://github.com/hapijs/oppsy/issues/17#issuecomment-430633689

**Comment by hueniverse** [comment]
Going to close for now. If this comes up again, please let me know.
